# Generated by Django 5.1.15 on 2026-09-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('adapter', models.CharField(blank=True, choices=[('', 'None (manual)'), ('google_places', 'Google Places API adapter'), ('openstreetmap', 'OpenStreetMap adapter'), ('official_website', 'Official website adapter'), ('business_submission', 'Business submission adapter'), ('seed_json', 'Seed JSON importer')], max_length=64)),
                ('storage_policy', models.CharField(choices=[('canonical', 'Canonical – we own the data, full persistence'), ('licensed', 'Licensed – persistence allowed with attribution'), ('reference', 'Reference only – store IDs, fetch content live')], default='canonical', max_length=16)),
                ('attribution_required', models.BooleanField(default=False)),
                ('attribution_text', models.CharField(blank=True, max_length=255)),
                ('sync_interval_hours', models.PositiveIntegerField(blank=True, help_text='Hours between syncs. Null = event-driven / on-demand only.', null=True)),
                ('api_limit_note', models.CharField(blank=True, help_text='Reminder of provider rate/storage limits.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='sources_sou_slug_126748_idx'), models.Index(fields=['adapter'], name='sources_sou_adapter_49a89a_idx')],
            },
        ),
    ]
