# Generated by Django 5.1.15 on 2026-09-25 02:03

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('communities', '0001_initial'),
        ('sources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, db_index=True, max_length=128)),
                ('province', models.CharField(blank=True, db_index=True, max_length=64)),
                ('postal_code', models.CharField(blank=True, db_index=True, max_length=16)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=32)),
                ('website', models.URLField(blank=True, max_length=512)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending review'), ('temporarily_closed', 'Temporarily closed'), ('permanently_closed', 'Permanently closed'), ('inactive', 'Inactive / deactivated')], db_index=True, default='active', max_length=32)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified'), ('reported', 'Reported'), ('rejected', 'Rejected')], db_index=True, default='unverified', max_length=16)),
                ('verification_method', models.CharField(blank=True, max_length=64)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='places', to='categories.category')),
                ('communities', models.ManyToManyField(blank=True, related_name='places', to='communities.community')),
                ('created_by_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_places', to='sources.source')),
                ('merged_into', models.ForeignKey(blank=True, help_text='If this place was deduplicated, the surviving canonical place.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_candidates', to='places.place')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_places', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'monday'), (1, 'tuesday'), (2, 'wednesday'), (3, 'thursday'), (4, 'friday'), (5, 'saturday'), (6, 'sunday')])),
                ('opens', models.TimeField(blank=True, null=True)),
                ('closes', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='places.place')),
            ],
            options={
                'ordering': ['day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='PlaceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.community')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('duplicate', 'Possible duplicate'), ('data_quality', 'Data quality issue')], default='duplicate', max_length=32)),
                ('confidence', models.FloatField(default=0.0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('other_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flagged_against', to='places.place')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='places.place')),
            ],
        ),
        migrations.CreateModel(
            name='SourceReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='Provider-native id, e.g. Google Place ID.', max_length=255)),
                ('source_url', models.URLField(blank=True, max_length=512)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_references', to='places.place')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='sources.source')),
            ],
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['city', 'status'], name='places_plac_city_d7ca5e_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['province', 'status'], name='places_plac_provinc_37ac78_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['normalized_name', 'phone'], name='places_plac_normali_8bb5bd_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['verification_status'], name='places_plac_verific_28b6c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.CheckConstraint(condition=models.Q(('location__isnull', False), models.Q(('latitude__isnull', False), ('longitude__isnull', False)), _connector='OR'), name='place_needs_coordinates'),
        ),
        migrations.AlterUniqueTogether(
            name='openinghours',
            unique_together={('place', 'day_of_week')},
        ),
        migrations.AlterUniqueTogether(
            name='placecategory',
            unique_together={('place', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='placecommunity',
            unique_together={('place', 'community')},
        ),
        migrations.AddIndex(
            model_name='placeflag',
            index=models.Index(fields=['resolved', 'reason'], name='places_plac_resolve_e24ee8_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcereference',
            index=models.Index(fields=['provider', 'external_id'], name='places_sour_provide_9dd5ab_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcereference',
            index=models.Index(fields=['place'], name='places_sour_place_i_ce2900_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sourcereference',
            unique_together={('provider', 'external_id')},
        ),
    ]
