# Generated by Django 5.1.15 on 2026-09-25 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('communities', '0001_initial'),
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_type', models.CharField(choices=[('suggest_place', 'Suggest a new place'), ('report_closed', 'Report closed business'), ('report_incorrect', 'Report incorrect information'), ('address_correction', 'Suggest address correction'), ('category_suggestion', 'Suggest category'), ('community_suggestion', 'Suggest community association')], max_length=32)),
                ('suggested_name', models.CharField(blank=True, max_length=255)),
                ('suggested_phone', models.CharField(blank=True, max_length=32)),
                ('suggested_website', models.URLField(blank=True)),
                ('suggested_address', models.CharField(blank=True, max_length=255)),
                ('suggested_city', models.CharField(blank=True, max_length=128)),
                ('suggested_province', models.CharField(blank=True, max_length=64)),
                ('suggested_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('suggested_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('message', models.TextField(blank=True)),
                ('submitter_email', models.EmailField(blank=True, max_length=254)),
                ('submitter_name', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='submissions', to='categories.category')),
                ('communities', models.ManyToManyField(blank=True, related_name='submissions', to='communities.community')),
                ('created_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_from_submission', to='places.place')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='places.place')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'submission_type'], name='submissions_status_de38bf_idx')],
            },
        ),
    ]
