# Generated by Django 5.1.15 on 2026-09-25 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='success', max_length=16)),
                ('query', models.CharField(blank=True, max_length=255)),
                ('processed', models.PositiveIntegerField(default=0)),
                ('created', models.PositiveIntegerField(default=0)),
                ('updated', models.PositiveIntegerField(default=0)),
                ('flagged', models.PositiveIntegerField(default=0, help_text='Possible duplicates sent to manual review.')),
                ('rejected', models.PositiveIntegerField(default=0)),
                ('errors', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='sources.source')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['source', '-started_at'], name='synchroniza_source__578f60_idx')],
            },
        ),
    ]
